matrix:
    include:
      - language: go
        go:
          - 1.x
        script:
          - go build code/Golang/main.go
      
      - language: ruby 
        rvm:
          - 2.5.0 
        script:
          - ruby code/Ruby/gol.rb
      
      - language: c 
        before_install:
          - sudo apt-get install -y lua5.2
        script:
          - lua code/Lua/GameOfLife.lua
